import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram } from "react-icons/ai"
import Image from 'next/image'
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web-1-1.png"
import { useState } from 'react'


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Akash Hubale Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>deleveopdbyAkash</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' /></li>
              <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>

          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Akash Hubale</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Web Developer and designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800  dark:text-gray-200  md:text-xl max-w-xl mx-auto'>  Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <a href="https://twitter.com/Akashhubale45"><AiFillTwitterCircle /></a>
            <a href="https://www.linkedin.com/in/akash-hubale-34b04122b/"><AiFillLinkedin /></a>
            <a href="https://www.instagram.com/akash_5_0_5/"> <AiFillInstagram /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>
        <section >
          <div >
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a web developer and
              designer, I've done work for my
              <span className="text-teal-500"> personal </span>
              <span className="text-teal-500"> projects </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including web development
              and programming.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center  shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image className='mx-auto' src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 '>Illustator</p>
              <p className='text-gray-800 py-1 '>Figma</p>
              <p className='text-gray-800 py-1 '>Photoshop</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image className='mx-auto' src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>  Code your dream project</h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className='py-4 text-teal-600'> tools I use</h4>
              <p className='text-gray-800 py-1 '>Next js</p>
              <p className='text-gray-800 py-1 '>Node js</p>
              <p className='text-gray-800 py-1 '>Mongodb</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image className='mx-auto' src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              {/* <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 '>Illustator</p>
              <p className='text-gray-800 py-1 '>Figma</p>
              <p className='text-gray-800 py-1 '>Photoshop</p> */}
            </div>

          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a web developer and
              dsigner, I've done work for my
              <span className="text-teal-500"> personal </span>
              <span className="text-teal-500"> projects </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <h3 className='text-xl py-1 dark:text-white'>yelpcamp</h3>
            <a href="https://github.com/akashhubale/yelpcamp-Akash" className='text-teal-500 '>Git Hub link</a>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1' >
              <Image src={web1} width={300} height={300} />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
